service: lambda-jvn-alert

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  profile: lambda
  memorySize: 128
  timeout: 20

custom: ${file(./env.yml)}
functions:
  alert:
    handler: handler.alert
    environment:
      hookUrl: ${self:custom.hookUrl}
      venderId: ${self:custom.venderId}
    events:
      - cron(0 0 * * ? *)